name: Packaging
on: pull_request

jobs:
  release-tarball:
    runs-on: ubuntu-18.04
    name: Build release tarball
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
          coverage: none
      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.12.3/krankerl_0.12.3_amd64.deb
          sudo dpkg -i krankerl_0.12.3_amd64.deb
      - name: Package app
        run: krankerl package
      - uses: actions/upload-artifact@v2
        with:
          path: build/artifacts/contacts.tar.gz
          if-no-files-found: error
